### ISSUE TITLE
What solarized theme is used in the screenshot?

### ISSUE THREAD

**Issue by hasufell** [sheoak/neomutt-powerline-nerdfonts#4]
The neomutt shipped theme `mutt-colors-solarized-dark-16.muttrc` looks very different here. Is that the one that was used?

**Comment by sheoak** [comment]
Hi, sorry, for some reason I didn't get notified of your issues.

You are free to use a different theme. I'm not sure which one I used but I remember having some trouble getting something working everywhere. The neomutt repository has evolved since and I might have to update mine at one point. For now it works for me, what is different for you?

**Comment by sheoak** [comment]
I'm closing, having no reply, feel free to reopen.
